### ISSUE TITLE
Map View and Statistics

### ISSUE THREAD

**Issue by Nihalh55** [gurupunskill/how-india-lives#13]
- [x] Work on graphs
    - [x] Parsing function
    - [x] Pie charts for HLPCA
    - [x] Bar graphs for comparing districts
- [x] Map View
    - [x] District level view of maps
    - [x] Comparison Map view for districts per state
    - [x] Comparison Map view for states
    - [x] Options to select features to be compared. 
- [x] Make State Table Information
        You have two options.
    - [x] Sum the values and dump in a json. Or create a state table with full columns. (Json preferred)

**Comment by Nihalh55** [comment]
Step 1 done.

**Comment by Nihalh55** [comment]
Will be using the following for percentage pie charts and other graphs:

https://codepen.io/VikasSharma/pen/oGLBEd
https://developers.google.com/chart/interactive/docs/gallery/barchart

**Comment by gurupunskill** [comment]
Resources for development:
 1. We need to set up an api key to use google maps. [here](https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings) and [here](https://developers.google.com/maps/documentation/javascript/get-api-key)
2. Use Google charts for the graphs. [here](https://developers.google.com/chart/interactive/docs/)
3. The maps are also Google _geocharts_. [here](https://developers.google.com/chart/interactive/docs/gallery/geochart)
    Implementation of this is available [here](https://codepen.io/vsvaibhav2016/pen/jrrOJk). Note that this is a state level implementation and we need district.
    Also, check out anymaps. I read about it somehwere. It also has a nice api.
